version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    depends_on:
      - jupyter
      - mariadb
      - nextcloud
      - gitlab

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlRootPassword_hbQYe9z21M87EOE
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlRootPassword_hbQYe9z21M87EOE
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nc_user
      - MYSQL_PASSWORD=nc_password
    depends_on:
      - mariadb

  jupyter:
    build: ./jupyter
    working_dir: /notebooks
    container_name: jupyter
    volumes:
      - ./jupyter/notebooks:/opt/notebooks
    ports:
      - 8888:8888
    command: jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='anhnt123' --NotebookApp.base_url='/jupyter'

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: "misr-server"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://misr-server/gitlab'

    
 