version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    depends_on:
      - jupyter
      - mariadb
      - nextcloud
      - gitlab
      - wordpress

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${NEXTCLOUD_DB}"
      MYSQL_USER: "${NEXTCLOUD_USER}"
      MYSQL_PASSWORD: "${NEXTCLOUD_PASSWORD}"
    depends_on:
      - mariadb

  jupyter:
    build: ./jupyter
    working_dir: /notebooks
    container_name: jupyter
    volumes:
      - ./jupyter/notebooks:/opt/notebooks
    command: jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=80 --no-browser --allow-root --NotebookApp.token='anhnt123' --NotebookApp.base_url='/jupyter'
    
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: "${SERVER_NAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${SERVER_NAME}/gitlab'
  
  wordpress:
    build: ./wordpress
    container_name: wordpress
    environment:
      WP_SUBDIRECTORY: "${WP_SUBDIRECTORY}"
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://${SERVER_NAME}/blog');
        define('WP_SITEURL','http://${SERVER_NAME}/blog');
    depends_on:
      - mariadb