version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    depends_on:
      # - jupyter
      - mariadb
      - nextcloud
      # - gitlab

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlRootPassword_hbQYe9z21M87EOE
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlRootPassword_hbQYe9z21M87EOE
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nc_user
      - MYSQL_PASSWORD=nc_password
    depends_on:
      - mariadb

  jupyter:
    build: ./jupyter
    working_dir: /notebooks
    volumes:
      - ./jupyter/notebooks:/opt/notebooks
    ports:
      - 8888:8888
    command: jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='anhnt123' --NotebookApp.base_url='/jupyter'

  # # Gitlab Setup
  # gitlab:
  #   restart: always
  #   image: gitlab/gitlab-ce:latest
  #   container_name: gitlab
  #   volumes:
  #     - ./gitlab/config:/etc/gitlab:Z
  #     - ./gitlab/logs:/var/log/gitlab:Z
  #     - ./gitlab/data:/var/opt/gitlab:Z
  #     - ./gitlab/backups:/mnt/backups/gitlab:Z
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       # URL
  #       external_url 'http://misr-desktop:8080/gitlab'
  #       # Backup directory
  #       gitlab_rails['backup_path'] = '/mnt/backups/gitlab'
  #       # Timezone
  #       gitlab_rails['time_zone'] = 'Asia/Tokyo'
  #       # E-mail
  #       gitlab_rails['smtp_enable'] = true
  #       gitlab_rails['smtp_address'] = "smtp.gmail.com"
  #       gitlab_rails['smtp_port'] = 587
  #       gitlab_rails['smtp_user_name'] = "user@gmail.com"
  #       gitlab_rails['smtp_password'] = "PASSWORD"
  #       gitlab_rails['smtp_domain'] = "smtp.gmail.com"
  #       gitlab_rails['smtp_authentication'] = "login"
  #       gitlab_rails['smtp_enable_starttls_auto'] = true
  #       gitlab_rails['smtp_tls'] = false
  #       gitlab_rails['smtp_openssl_verify_mode'] = 'peer' # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
  #     # Add any other gitlab.rb configuration here, each on its own line
  #     GITLAB_RELATIVE_URL_ROOT: /gitlab
