FROM continuumio/miniconda3

RUN conda install jupyter -y --quiet && mkdir /opt/notebooks
#&&\
#  conda install -y -c conda-forge matplotlib tensorflow &&\
#  conda install -y -c anaconda pandas scikit-learn seaborn